# Reference: https://github.com/i3/i3/blob/next/etc/config

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-a = 'workspace A'
alt-c = 'workspace C'
alt-h = 'workspace H'
alt-j = 'workspace J'
alt-k = 'workspace K'
alt-o = 'workspace O'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-a = 'move-node-to-workspace A'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-h = 'move-node-to-workspace H'
alt-shift-j = 'move-node-to-workspace J'
alt-shift-k = 'move-node-to-workspace K'
alt-shift-o = 'move-node-to-workspace O'

alt-f = 'fullscreen'

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
A = 'secondary'
C = 'secondary'
H = 'secondary'
J = 'secondary'
K = 'secondary'
O = 'secondary'
